### ISSUE TITLE
random ciou calculation

### ISSUE THREAD

**Issue by ghost** [shvdiwnkozbw/Multi-Source-Sound-Localization#2]
Hi there,

may i ask have you tried the ciou@0.5 accuracy result when always choosing the whole image region as positive?
I found it quite high compared with experiment result. (60.8% for my test data, which is 250 samples randomly chosen from 5k annotated sound flickr dataset in Learning to Localize Sound Source in Visual Scenes CVPR18

**Comment by ghost** [comment]
I just set new/main.py function cal_ciou parameter thres as 0
Thank you in advance )

**Comment by shvdiwnkozbw** [comment]
The accuracy result under threshold 0 is closely related to the sounding area of test data. If the test data contain a large amount of audiovisual pairs where the sounding areas occupy nearly the whole region in the image, then setting thres as 0 will result in very high accuracy. Therefore, sometimes the quantitative result cannot well reflect the model's ability for localization, but the qualitative visualizations make more sense.

**Comment by ghost** [comment]
@shvdiwnkozbw 
thank you
