### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by ghost** [shvdiwnkozbw/Multi-Source-Sound-Localization#3]
hi
sorry to bother (

i used 10k image-sound pairs from sound-flickcr dataset and used 250 from labeled images for evaluation. While the ciou result is not bad, the visualization result is not good (quite a mess). is it convenient to release the list of index you trained with (as part of indexes of https://projects.csail.mit.edu/soundnet/#data )
i trained 20 epochs both for stage 1 and 2 

thank you

**Comment by shvdiwnkozbw** [comment]
Hi 

Here is the Baidu Pan link for the training data, hope this can help you
https://pan.baidu.com/s/1J2gxMsaZxgE1V4S3o3Swrg
with password: recp

Best

**Comment by ghost** [comment]
thank you

**Comment by sunwell1994** [comment]
> Hi
> 
> Here is the Baidu Pan link for the training data, hope this can help you https://pan.baidu.com/s/1J2gxMsaZxgE1V4S3o3Swrg with password: recp
> 
> Best

This is awesome. Do you have other links to download the data? Baidu Pan is so slow.

**Comment by shvdiwnkozbw** [comment]
https://drive.google.com/file/d/1Y8nqyIxvyQtPbbfcpiSIRxBdJQ56Z3B5/view?usp=sharing
https://drive.google.com/file/d/1oAlC44aDWwSO8w9spoYCfJVvKeAlyYDh/view?usp=sharing
This is the google drive link. Hope this can help you
